var express = require("express");
var router = express.Router();
var Connection = require("../config/database-config");
/* GET users listing. */
router.get("/", function(req, res, next) {
  res.send("Clients are here");
});
router.get("/getClients", function(req, res, next) {
  Connection.query("SELECT * FROM Priests", function(error, results, fields) {
    if (error) throw error;
    console.log("The solution is: ", results);
    res.send(results);
  });
});
router.post("/postTest", async function(req, res, next) {
  let AllClientsData = req.body;
  console.log(req.body);

  const values = AllClientsData.map(eachData => [
    eachData.Name,
    eachData.info,
    eachData.GraduationYearID,
    eachData.Email,
    eachData.LocationX,
    eachData.LocationY,
    eachData.fatherOfConfession,
    eachData.servantFollowing,
    eachData.clientCategoryID,
    eachData.chomosya,
    eachData.MobilePhone,
    eachData.HomePhone,
    eachData.fatherPhone,
    eachData.motherPhone,
    eachData.Class,
    eachData.Zone,
    eachData.streetName,
    eachData.floorNumber,
    eachData.buildingNumber,
    eachData.flatNumber,
    eachData.streetDetails
  ]);
  console.log(values);

  await Connection.query(
    "INSERT INTO `Clients` (`Name`, `info`, `GraduationYearID`, `Email`, `LocationX`, `LocationY`, `fatherOfConfession`, `servantFollowing`, `clientCategoryID`, `chomosya`, `MobilePhone`, `HomePhone`, `fatherPhone`, `motherPhone`, `Class`, `Zone`, `streetName` , `floorNumber` , `buildingNumber` , `flatNumber` , `streetDetails`) VALUES ?",
    [values],
    function(error, results, fields) {
      if (error) throw error;
      console.log("The solution is: ", results);
      res.send(results);
    }
  );
});

router.get("/postClients", function(req, res, next) {
  var AllClients = [
    {
      counter: "1",
      zone: "A",
      name: "ألبرت ماجد صفوت",
      servantFollowing: "مايكل وحيد",
      status: "وش قفص",
      notes: "",
      buildingNumber: "26أ",
      streetName: "الجميل",
      floorNumber: "3",
      flatNumber: "شقة واحدة",
      MobilePhone: "01207420910",
      HomePhone: "25901872",
      birthDate: "37612",
      fatherOfConfession: "أ.انجيلوس",
      chomosya: "شماس",
      school: "صحارا",
      fatherPhone: "01212241105-01001994284",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "2",
      zone: "A",
      name: "بنيامين شنودة صبرى",
      servantFollowing: "ابراهيم صموئيل",
      status: "وش قفص",
      notes: "",
      buildingNumber: "1",
      streetName: "الجميل",
      floorNumber: "7",
      flatNumber: "33",
      MobilePhone: "01128999111",
      HomePhone: "",
      birthDate: "37700",
      fatherOfConfession: "أ.موسى(العذراء الفجالة)",
      chomosya: "شماس",
      school: "البطريركية",
      fatherPhone: "1128999222-01113939385",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "3",
      zone: "A",
      name: "بيير جورج ألبير",
      servantFollowing: "ابراهيم صموئيل",
      status: "وش قفص",
      notes: "",
      buildingNumber: "2أ",
      streetName:
        "الجميل - عمارة امام روز ماري عمارة بتاع العطور والحلاق-امام الكنيسة",
      floorNumber: "4",
      flatNumber: "10",
      MobilePhone: "01273721749",
      HomePhone: "",
      birthDate: "37375",
      fatherOfConfession: "أ.برسوم",
      chomosya: "شماس",
      school: "البطريركية",
      fatherPhone: "1223657486",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "4",
      zone: "A",
      name: "جرجس ممدوح فرج",
      servantFollowing: "مايكل وحيد",
      status: "وش قفص",
      notes: "",
      buildingNumber: "1",
      streetName: "الجميل",
      floorNumber: "8",
      flatNumber: "38",
      MobilePhone: "01225692346",
      HomePhone: "25923135",
      birthDate: "37659",
      fatherOfConfession: "أ.يوسف",
      chomosya: "شماس",
      school: "القديس ميخائيل",
      fatherPhone: "1270426817",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "5",
      zone: "A",
      name: "عبد المسيح أيمن توفيق",
      servantFollowing: "بيتر ميلاد",
      status: "اخوة رب",
      notes: "",
      buildingNumber: "15",
      streetName: "غالي",
      floorNumber: "6",
      flatNumber: "16",
      MobilePhone: "1223741743",
      HomePhone: "1150746356",
      birthDate: "37390",
      fatherOfConfession: "",
      chomosya: "",
      school: "الفاروق عمر ",
      fatherPhone: "01272246632-01271334451",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "6",
      zone: "A",
      name: "يوسف عماد جمال",
      servantFollowing: "بيتر ميلاد",
      status: "وسطى",
      notes: "",
      buildingNumber: "30",
      streetName: "الجميل",
      floorNumber: "3",
      flatNumber: "10",
      MobilePhone: "1271217203",
      HomePhone: "27877012",
      birthDate: "",
      fatherOfConfession: "",
      chomosya: "",
      school: "",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "7",
      zone: "A",
      name: "يوسف عماد يوسف ذكرى",
      servantFollowing: "بيتر محسن - بيتر جورج",
      status: "وسطى",
      notes: "",
      buildingNumber: "13",
      streetName: "الجد",
      floorNumber: "2",
      flatNumber: "11",
      MobilePhone: "1227100453",
      HomePhone: "",
      birthDate: "37901",
      fatherOfConfession: "أ.يوسف",
      chomosya: "شماس",
      school: "الفاروق عمر",
      fatherPhone: "1224909016",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "8",
      zone: "B",
      name: "أبانوب عادل مكرم",
      servantFollowing: "بيتر ميلاد",
      status: "اخوة رب",
      notes: "",
      buildingNumber: "2",
      streetName: "زقاق حبيب شلبى (فوق مكتبة سرينا بجانب فطاطرى العمدة)",
      floorNumber: "2",
      flatNumber: "على الشمال",
      MobilePhone: "01288799399",
      HomePhone: "11210074926",
      birthDate: "37618",
      fatherOfConfession: "أ.أنجيلوس",
      chomosya: "",
      school: "ثمرة التوفيق",
      fatherPhone: "1200515571",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "9",
      zone: "B",
      name: "بيشوى جورج سميح",
      servantFollowing: "بيشوى ميخائيل",
      status: "اخوة رب",
      notes: "متوسط الحضور",
      buildingNumber: "23",
      streetName: "حبيب شلبى - الجدة (البيت في المرج) - ت",
      floorNumber: "الأرضى",
      flatNumber: "",
      MobilePhone: "1207887038",
      HomePhone: "28870871",
      birthDate: "37723",
      fatherOfConfession: "",
      chomosya: "",
      school: "المنارة بالمرج",
      fatherPhone: "1228381451",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "10",
      zone: "B",
      name: "فادي عبد الشهيد",
      servantFollowing: "بيتر ميلاد",
      status: "اخوة رب",
      notes: "",
      buildingNumber: "31",
      streetName: "حبيب شلبى",
      floorNumber: "ارضى",
      flatNumber: "---",
      MobilePhone: "1205464054",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "ا/انجيلوس",
      chomosya: "",
      school: "السلام",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "11",
      zone: "B",
      name: "ميلاد ثابت نظير",
      servantFollowing: "بيتر ميلاد",
      status: "اخوة رب",
      notes: "مستديم الحضور",
      buildingNumber: "21",
      streetName: "حارة البير الحلوة- سوق الزلط",
      floorNumber: "3",
      flatNumber: "شقة على الشمال",
      MobilePhone: "1202104552",
      HomePhone: "25886803",
      birthDate: "37937",
      fatherOfConfession: "أ.أنجيلوس",
      chomosya: "شماس",
      school: "اليوسيفية",
      fatherPhone: "01007954169-01271075506",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "12",
      zone: "B",
      name: "مينا ثابت مينا",
      servantFollowing: "بيتر ميلاد",
      status: "اخوة رب",
      notes: "مشاكل مع الاب",
      buildingNumber: "6",
      streetName: "بركة الحاجب متفرع من شارع الجد",
      floorNumber: "2",
      flatNumber: "7",
      MobilePhone: "1224041255",
      HomePhone: "",
      birthDate: "37447",
      fatherOfConfession: "أ.أنجيلوس",
      chomosya: "",
      school: "الفاروق عمر",
      fatherPhone: "1281415178",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "13",
      zone: "B",
      name: "مينا عزت راغب",
      servantFollowing: "ابراهيم صموئيل",
      status: "وش قفص",
      notes: "",
      buildingNumber: "12أ",
      streetName: "السلحدار متفرع من بركة الرطل",
      floorNumber: "6",
      flatNumber: "6",
      MobilePhone: "01206787986",
      HomePhone: "",
      birthDate: "37666",
      fatherOfConfession: "",
      chomosya: "",
      school: "المارونية",
      fatherPhone: "",
      motherPhone: "1223777002",
      class: "1"
    },
    {
      counter: "14",
      zone: "B",
      name: "يوسف عادل فضل",
      servantFollowing: "مايكل وحيد",
      status: "وش قفص",
      notes: "",
      buildingNumber: "2",
      streetName: "سكة بركة الطوابة شارع الجد أمام مدرسة التوفيق بنات",
      floorNumber: "8",
      flatNumber: "16",
      MobilePhone: "01289774117",
      HomePhone: "",
      birthDate: "37665",
      fatherOfConfession: "أ.موسى",
      chomosya: "",
      school: "المارونية",
      fatherPhone: "01225852434-01223382731",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "15",
      zone: "B",
      name: "ملاك عازر",
      servantFollowing: "بيتر ميلاد",
      status: "اخوة رب",
      notes: "",
      buildingNumber: "39",
      streetName: "كامل صدقي - جراج البطل - بنك QNB",
      floorNumber: "",
      flatNumber: "",
      MobilePhone: "01223236482",
      HomePhone: "",
      birthDate: "November11",
      fatherOfConfession: "2002",
      chomosya: "أ.أنجيلوس",
      school: "",
      fatherPhone: "الفاروق عمر",
      motherPhone: "",
      class: ""
    },
    {
      counter: "16",
      zone: "B",
      name: "يوسف ممدوح",
      servantFollowing: "بيتر محسن - بيتر جورج",
      status: "وسطى",
      notes: "مشكلة عصبية",
      buildingNumber: "44",
      streetName: "حبيب شلبي ",
      floorNumber: "7",
      flatNumber: "26",
      MobilePhone: "01001488941",
      HomePhone: "225938156",
      birthDate: "36900",
      fatherOfConfession: "",
      chomosya: "",
      school: "صحارا",
      fatherPhone: "1001488941",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "17",
      zone: "B",
      name: "يوسف نادر ميلاد",
      servantFollowing: "مايكل وحيد",
      status: "وش قفص",
      notes: "",
      buildingNumber: "4",
      streetName: "يوسف سليمان",
      floorNumber: "1",
      flatNumber: "23",
      MobilePhone: "1271773832",
      HomePhone: "225919206",
      birthDate: "37358",
      fatherOfConfession: "أ.أنجيلوس",
      chomosya: "",
      school: "صحارا",
      fatherPhone: "1272200861",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "18",
      zone: "B",
      name: "موسى عزت راجى",
      servantFollowing: "بيتر ميلاد",
      status: "اخوة رب",
      notes: "",
      buildingNumber: "10",
      streetName: "حارة أحمد نافع بجانب محل الشراع المصرى للملابس",
      floorNumber: "3",
      flatNumber: "4",
      MobilePhone: "٠١٢٨٤١٣١٩٢٢",
      HomePhone: "",
      birthDate: "37718",
      fatherOfConfession: "",
      chomosya: "",
      school: "ثمرة التوفيق",
      fatherPhone: "1281590087",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "19",
      zone: "C",
      name: "فيلوباتير أمير اسحق",
      servantFollowing: "مايكل وحيد",
      status: "وش قفص",
      notes: "",
      buildingNumber: "4",
      streetName: "كوم الريش - يوسف وهبة ",
      floorNumber: "9",
      flatNumber: "15",
      MobilePhone: "1208740964",
      HomePhone: "",
      birthDate: "May1",
      fatherOfConfession: "2003",
      chomosya: "أ. اغسطين - مطرانية الجيزة",
      school: "شماس",
      fatherPhone: "البطريركية",
      motherPhone: "1225423223",
      class: ""
    },
    {
      counter: "20",
      zone: "C",
      name: "برسوم رضا أندراوس",
      servantFollowing: "مايكل وحيد",
      status: "وش قفص",
      notes: "",
      buildingNumber: "21",
      streetName: "يوسف وهبة",
      floorNumber: "9",
      flatNumber: "40",
      MobilePhone: "1281837860",
      HomePhone: "27864564",
      birthDate: "37483",
      fatherOfConfession: "أ.أنجيلوس",
      chomosya: "شماس",
      school: "البطريركية",
      fatherPhone: "1205993995",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "21",
      zone: "C",
      name: "تونى آرتين",
      servantFollowing: "مايكل وحيد",
      status: "مستديمى الغياب ",
      notes: "مارونية - سريان",
      buildingNumber: "25",
      streetName: "بركة الرطل",
      floorNumber: "5",
      flatNumber: "15",
      MobilePhone: "٠١١٥٤٤٨٢٨١٣",
      HomePhone: "25887533",
      birthDate: "37602",
      fatherOfConfession: "",
      chomosya: "",
      school: "القديس ميخائيل",
      fatherPhone: "1128877239",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "22",
      zone: "C",
      name: "ديفيد إسحق أديب",
      servantFollowing: "بيتر محسن - بيتر جورج",
      status: "وسطى",
      notes: "",
      buildingNumber: "31",
      streetName: "الظاهر",
      floorNumber: "6",
      flatNumber: "شقة على الشمال",
      MobilePhone: "01275796208",
      HomePhone: "",
      birthDate: "37656",
      fatherOfConfession: "",
      chomosya: "",
      school: "ثمرة التوفيق",
      fatherPhone: "1223870927",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "23",
      zone: "C",
      name: "فادى عادل عوض",
      servantFollowing: "بيتر ميلاد",
      status: "اخوة رب",
      notes: "",
      buildingNumber: "6",
      streetName: "وقف الخربوطلي -عمارة سيراميك البطل- قبل عمارة ايهاب ايميل",
      floorNumber: "3",
      flatNumber: "4",
      MobilePhone: "1119173051",
      HomePhone: "",
      birthDate: "37433",
      fatherOfConfession: "أ.أنجيلوس",
      chomosya: "",
      school: "القديس ميخائيل",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "24",
      zone: "C",
      name: "مارتن شريف رسمى",
      servantFollowing: "مايكل وحيد",
      status: "وش قفص",
      notes: "",
      buildingNumber: "21",
      streetName: "يوسف وهبة",
      floorNumber: "5",
      flatNumber: "13",
      MobilePhone: "1226791796",
      HomePhone: "25885163",
      birthDate: "37509",
      fatherOfConfession: "لا",
      chomosya: "لا",
      school: "صحارا",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "25",
      zone: "C",
      name: "مكسيموس أشرف عجيب",
      servantFollowing: "مايكل وحيد",
      status: "وش قفص",
      notes: "",
      buildingNumber: "21",
      streetName: "يوسف وهبة",
      floorNumber: "10",
      flatNumber: "يمين آخر الطرقة فى الوش",
      MobilePhone: "01226584796",
      HomePhone: "27876705",
      birthDate: "37485",
      fatherOfConfession: "لا",
      chomosya: "شماس",
      school: "صحارا",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "26",
      zone: "C",
      name: "ميلاد رمسيس حبيب",
      servantFollowing: "بيتر محسن - بيتر جورج",
      status: "وسطى",
      notes: "",
      buildingNumber: "7",
      streetName: "حارة نسب (الحارة اللى جنب كنيسة رابطة القدس)",
      floorNumber: "1",
      flatNumber: "3يمين",
      MobilePhone: "1284572650",
      HomePhone: "25934497",
      birthDate: "38140",
      fatherOfConfession: "أ.تادرس",
      chomosya: "شماس",
      school: "الراعى الصالح",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "27",
      zone: "C",
      name: "روبير رأفت رؤوف",
      servantFollowing: "مايكل وحيد",
      status: "وش قفص",
      notes: "",
      buildingNumber: "3",
      streetName: "القبيسى",
      floorNumber: "3",
      flatNumber: "18- شمال",
      MobilePhone: "01285637372",
      HomePhone: "27876637",
      birthDate: "37853",
      fatherOfConfession: "ا.برسوم",
      chomosya: "",
      school: "صحارا",
      fatherPhone: "1223726637",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "28",
      zone: "C",
      name: "فادى أيوب",
      servantFollowing: "بيشوى ميخائيل",
      status: "اخوة رب",
      notes: "وسطى",
      buildingNumber: "147أ",
      streetName: "شاع رمسيس",
      floorNumber: "الأرضى",
      flatNumber: "",
      MobilePhone: "1223506403",
      HomePhone: "",
      birthDate: "37551",
      fatherOfConfession: "ا.موسى موسى",
      chomosya: "شماس",
      school: "مدرسة الازبكية",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "29",
      zone: "C",
      name: "بولا جمال نصيف",
      servantFollowing: "ابراهيم صموئيل",
      status: "مستديمى الغياب ",
      notes: "",
      buildingNumber: "30",
      streetName: "القبيسى(بيت الجدة) - بيته في الزيتون - ت",
      floorNumber: "الأخير",
      flatNumber: "شمال",
      MobilePhone: "",
      HomePhone: "",
      birthDate: "37923",
      fatherOfConfession: "",
      chomosya: "",
      school: "آمون",
      fatherPhone: "1220335724",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "30",
      zone: "D",
      name: "كيرلس عادل نان",
      servantFollowing: "مايكل وحيد",
      status: "وش قفص",
      notes: "",
      buildingNumber: "37",
      streetName: "الظاهر",
      floorNumber: "1",
      flatNumber: "8",
      MobilePhone: "1201542323",
      HomePhone: "27874773",
      birthDate: "37606",
      fatherOfConfession: "أ.برسوم",
      chomosya: "شماس",
      school: "البطريركية",
      fatherPhone: "1224105242",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "31",
      zone: "D",
      name: "بولا هانى منقاريوس",
      servantFollowing: "مايكل وحيد",
      status: "وش قفص",
      notes: "",
      buildingNumber: "49",
      streetName: "القبيسى",
      floorNumber: "6",
      flatNumber: "يمين الأسانسير",
      MobilePhone: "1289220288",
      HomePhone: "1551359204",
      birthDate: "37808",
      fatherOfConfession: "أ.يوسف",
      chomosya: "شماس",
      school: "القديس ميخائيل",
      fatherPhone: "01065715787-01272379130",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "32",
      zone: "D",
      name: "توماس عماد موريس",
      servantFollowing: "مايكل وحيد",
      status: "وش قفص",
      notes: "",
      buildingNumber: "3",
      streetName: "السبع - عمارة استوديو آرتين",
      floorNumber: "3",
      flatNumber: "40",
      MobilePhone: "01206164394",
      HomePhone: "25939262",
      birthDate: "37357",
      fatherOfConfession: "أ.برسوم",
      chomosya: "شماس",
      school: "College De la Salle",
      fatherPhone: "1006621113",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "33",
      zone: "D",
      name: "جورج نزيه",
      servantFollowing: "بيشوى ميخائيل",
      status: "وش قفص",
      notes: "",
      buildingNumber: "50",
      streetName: "شارع القبيسى الظاهر",
      floorNumber: "3",
      flatNumber: "5",
      MobilePhone: "01270135283",
      HomePhone: "",
      birthDate: "january15",
      fatherOfConfession: "2003",
      chomosya: "ابونا انجيلوس",
      school: "شماس",
      fatherPhone: "المارونية",
      motherPhone: "",
      class: ""
    },
    {
      counter: "34",
      zone: "D",
      name: "عزيز عماد عونى",
      servantFollowing: "بيتر محسن - بيتر جورج",
      status: "وسطى",
      notes: "",
      buildingNumber: "8ب",
      streetName: "السبع (حارة بعد صيدلية أحمد عفيفى)",
      floorNumber: "4",
      flatNumber: "شقة على الشمال",
      MobilePhone: "01201602848",
      HomePhone: "27873244-27867147(جدته) ",
      birthDate: "37448",
      fatherOfConfession: "",
      chomosya: "",
      school: "القديس ميخائيل",
      fatherPhone: "1220409225",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "35",
      zone: "D",
      name: "كيرلس سمير كامل",
      servantFollowing: "ابراهيم صموئيل",
      status: "مستديمى الغياب ",
      notes: "",
      buildingNumber: "29",
      streetName: "القبيسى -ممر الريان- الجدة (بيته في عزبة النخل) - ت",
      floorNumber: "5",
      flatNumber: "آخر السلم",
      MobilePhone: "1201999387",
      HomePhone: "25883110",
      birthDate: "37790",
      fatherOfConfession: "أ.أنجيلوس",
      chomosya: "",
      school: "الفراعنة",
      fatherPhone: "1284756244",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "36",
      zone: "D",
      name: "كيرلس مجدى يسرى",
      servantFollowing: "بيتر محسن - بيتر جورج",
      status: "وش قفص",
      notes: "",
      buildingNumber: "4",
      streetName: "حمدى",
      floorNumber: "4",
      flatNumber: "19",
      MobilePhone: "01289731755",
      HomePhone: "",
      birthDate: "37853",
      fatherOfConfession: "أ.يوسف",
      chomosya: "",
      school: "القديس ميخائيل",
      fatherPhone: "1221240622",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "37",
      zone: "D",
      name: "ميلاد صفوت صموئيل",
      servantFollowing: "بيشوى ميخائيل",
      status: "اخوة رب",
      notes: "",
      buildingNumber: "86",
      streetName: "القبيسى",
      floorNumber: "7",
      flatNumber: "13",
      MobilePhone: "",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      chomosya: "",
      school: "",
      fatherPhone: "1276331578",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "38",
      zone: "D",
      name: "بيشوي نادر البير",
      servantFollowing: "بيتر محسن - بيتر جورج",
      status: "مستديمى الغياب ",
      notes: "",
      buildingNumber: "28",
      streetName: "صبري",
      floorNumber: "4",
      flatNumber: "43",
      MobilePhone: "01207406094",
      HomePhone: "1005668507",
      birthDate: "",
      fatherOfConfession: "",
      chomosya: "",
      school: "College De la Salle",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "39",
      zone: "E",
      name: "بولا ميلاد فاضل",
      servantFollowing: "بيتر محسن - بيتر جورج",
      status: "مستديمى الغياب ",
      notes: "",
      buildingNumber: "23",
      streetName: "صبرى",
      floorNumber: "11",
      flatNumber: "شقة واحدة",
      MobilePhone: "1022356116",
      HomePhone: "",
      birthDate: "37388",
      fatherOfConfession: "",
      chomosya: "",
      school: "Dover",
      fatherPhone: "1223010094",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "40",
      zone: "E",
      name: "بيير سركيس زرادليان",
      servantFollowing: "بيتر محسن - بيتر جورج",
      status: "وسطى",
      notes: "",
      buildingNumber: "13",
      streetName: "صبرى -المبنى مكون من عمارتين هو فى العمارة اللى على الشمال",
      floorNumber: "7",
      flatNumber: "75",
      MobilePhone: "1270405146",
      HomePhone: "27863743",
      birthDate: "37725",
      fatherOfConfession: "أ.موسى",
      chomosya: "",
      school: "Calestiano Marianne",
      fatherPhone: "1223817915",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "41",
      zone: "E",
      name: "جورج جوزيف باسيليوس",
      servantFollowing: "بيشوى ميخائيل",
      status: "وش قفص",
      notes: "",
      buildingNumber: "2",
      streetName: "ذهنى",
      floorNumber: "8",
      flatNumber: "جنب الأسانسير على الشمال",
      MobilePhone: "01000511905",
      HomePhone: "",
      birthDate: "37949",
      fatherOfConfession: "أ.تادرس",
      chomosya: "شماس",
      school: "صحارا",
      fatherPhone: "01148842688-01110023088",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "42",
      zone: "E",
      name: "جورج ملاك ناجح",
      servantFollowing: "بيشوى ميخائيل",
      status: "اخوة رب",
      notes: "مستديمى الغياب",
      buildingNumber: "10",
      streetName: "حمدى - مسافر البلد ( دراسة )",
      floorNumber: "أرضى",
      flatNumber: "",
      MobilePhone: "",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      chomosya: "",
      school: "",
      fatherPhone: "1105034780",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "43",
      zone: "E",
      name: "جوزيف عادل",
      servantFollowing: "بيتر محسن - بيتر جورج",
      status: "وسطى",
      notes: "",
      buildingNumber: "29",
      streetName: "شارع ذهني - اعلى ميكانيكي ايهاب",
      floorNumber: "5",
      flatNumber: "16",
      MobilePhone: "1270204560",
      HomePhone: "",
      birthDate: "August4",
      fatherOfConfession: "2003",
      chomosya: "أ. يوحنا - الفجالة",
      school: "شماس",
      fatherPhone: "القديس ميخائيل",
      motherPhone: "",
      class: ""
    },
    {
      counter: "44",
      zone: "E",
      name: "ستيفن اكرم",
      servantFollowing: "بيشوى ميخائيل",
      status: "وش قفص",
      notes: "مشكلة عصبية",
      buildingNumber: "32أ",
      streetName: "حمدي",
      floorNumber: "4",
      flatNumber: "شمال",
      MobilePhone: "1283833780",
      HomePhone: "",
      birthDate: "December24",
      fatherOfConfession: "2002",
      chomosya: "أ.أنجيلوس",
      school: "",
      fatherPhone: "المارونية",
      motherPhone: "",
      class: ""
    },
    {
      counter: "45",
      zone: "E",
      name: "كيرلس سامح فوزى",
      servantFollowing: "أنطوان سليمان",
      status: "وسطى",
      notes: "مشكلة فى السمع و الكلام",
      buildingNumber: "13",
      streetName: "صبرى -عمارة ابونا برسوم هو فى العمارة اللى على يمين",
      floorNumber: "1",
      flatNumber: "13",
      MobilePhone: "",
      HomePhone: "",
      birthDate: "37511",
      fatherOfConfession: "",
      chomosya: "",
      school: "مديحة كونسو",
      fatherPhone: "1207431517",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "46",
      zone: "E",
      name: "كيرلس وجدى وليم (منسي)",
      servantFollowing: "بيتر محسن - بيتر جورج",
      status: "وسطى",
      notes: "",
      buildingNumber: "13",
      streetName: "صبرى -عمارة ابونا برسوم هو فى العمارة اللى على يمين",
      floorNumber: "1",
      flatNumber: "12",
      MobilePhone: "01220689203",
      HomePhone: "25926445",
      birthDate: "37469",
      fatherOfConfession: "",
      chomosya: "",
      school: "الجلاء",
      fatherPhone: "01284838251-01211744522",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "47",
      zone: "E",
      name: "مينا هاني",
      servantFollowing: "بيتر ميلاد",
      status: "اخوة رب",
      notes: "",
      buildingNumber: "12",
      streetName: "حارة المرشدي البكرية - ",
      floorNumber: "6",
      flatNumber: "6",
      MobilePhone: "",
      HomePhone: "1272990834",
      birthDate: "",
      fatherOfConfession: "",
      chomosya: "",
      school: "السلام",
      fatherPhone: "1272990834",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "48",
      zone: "F",
      name: "فؤاد ميخائيل فؤاد",
      servantFollowing: "ابراهيم صموئيل",
      status: "وش قفص",
      notes: "",
      buildingNumber: "57",
      streetName: "عبد الحميد الديب - ميدان المماليك - خلفاوي - شبرا",
      floorNumber: "",
      flatNumber: "",
      MobilePhone: "0 121 165 7206",
      HomePhone: "",
      birthDate: "37529",
      fatherOfConfession: "أ.برسوم",
      chomosya: "شماس",
      school: "البطريركية",
      fatherPhone: "01223675212-01287080384",
      motherPhone: "01287080384",
      class: "1"
    },
    {
      counter: "49",
      zone: "F",
      name: "أندرو إيهاب",
      servantFollowing: "بيتر محسن - بيتر جورج",
      status: "وسطى",
      notes: "",
      buildingNumber: "28",
      streetName: "حمدي",
      floorNumber: "2",
      flatNumber: "9",
      MobilePhone: "1289200752",
      HomePhone: "",
      birthDate: "37838",
      fatherOfConfession: "ا/انجيلوس",
      chomosya: "",
      school: "المارونية",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "50",
      zone: "F",
      name: "جون هانى إسحاق",
      servantFollowing: "ابراهيم صموئيل",
      status: "مستديمى الغياب ",
      notes: "",
      buildingNumber: "1",
      streetName:
        "عند البنك الاهلى الى عند المستشفى الجوى الى عند KFC فى احمد سعيد ",
      floorNumber: "10",
      flatNumber: "100",
      MobilePhone: "1226202564",
      HomePhone: "",
      birthDate: "37666",
      fatherOfConfession: "ا/موسى",
      chomosya: "",
      school: "المعارف الحديثة لغات الزيتون",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "51",
      zone: "F",
      name: "فادي صبحي",
      servantFollowing: "بيشوى ميخائيل",
      status: "اخوة رب",
      notes: "فجالة",
      buildingNumber: "28",
      streetName:
        "محطة ناصر - معسكر - ش نور الدين سالم متفرع من ش الاشمولي - مدينة الاحلام",
      floorNumber: "4",
      flatNumber: "على السلم ",
      MobilePhone: "1210860635",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      chomosya: "",
      school: "",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "52",
      zone: "F",
      name: "كيرلس يوسف ماهر",
      servantFollowing: "بيشوى ميخائيل",
      status: "وش قفص",
      notes: "",
      buildingNumber: "219",
      streetName: "رمسيس",
      floorNumber: "5",
      flatNumber: "جنب الأسانسير ",
      MobilePhone: "1224254527",
      HomePhone: "27879736",
      birthDate: "37559",
      fatherOfConfession: "",
      chomosya: "",
      school: "المارونية",
      fatherPhone: "1229149846",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "53",
      zone: "F",
      name: "رائد حاتم",
      servantFollowing: "بيشوى ميخائيل",
      status: "اخوة رب",
      notes: "منسى",
      buildingNumber: "1",
      streetName: "طور سيناء - معرض علاء الدين - ميدان الظاهر",
      floorNumber: "ارضي",
      flatNumber: "3",
      MobilePhone: "",
      HomePhone: "1090157159",
      birthDate: "",
      fatherOfConfession: "",
      chomosya: "",
      school: "",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "54",
      zone: "F",
      name: "رامي حاتم",
      servantFollowing: "بيشوى ميخائيل",
      status: "اخوة رب",
      notes: "منسى",
      buildingNumber: "1",
      streetName: "طور سيناء - معرض علاء الدين - ميدان الظاهر",
      floorNumber: "ارضي",
      flatNumber: "3",
      MobilePhone: "",
      HomePhone: "1090157159",
      birthDate: "",
      fatherOfConfession: "",
      chomosya: "",
      school: "",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "55",
      zone: "F",
      name: "مينا حنا",
      servantFollowing: "بيشوى ميخائيل",
      status: "اخوة رب",
      notes: "وسطى",
      buildingNumber: "26",
      streetName: "السكاكيني",
      floorNumber: "ارضي",
      flatNumber: "---",
      MobilePhone: "1222774709",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      chomosya: "",
      school: "اسلام زاويد",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "56",
      zone: "F",
      name: "فيلوباتير عماد فابز",
      servantFollowing: "ابراهيم صموئيل",
      status: "مستديمى الغياب ",
      notes: "",
      buildingNumber: "239",
      streetName: "شارع رمسيس - غمرة ",
      floorNumber: "6",
      flatNumber: "27",
      MobilePhone: "01285109253",
      HomePhone: "1223416551",
      birthDate: "",
      fatherOfConfession: "",
      chomosya: "",
      school: "",
      fatherPhone: "",
      motherPhone: "",
      class: "1"
    },
    {
      counter: "1",
      class: "2",
      zone: "A",
      name: "مارك مدحت",
      buildingNumber: "1",
      streetName: "يوسف وهبى",
      floorNumber: "2",
      flatNumber: "4",
      MobilePhone: "01094324060",
      HomePhone: "25919845",
      birthDate: "37485",
      fatherOfConfession: "أبونا أنجيلوس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "صحارا",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "2",
      class: "2",
      zone: "A",
      name: "مينا عماد حليم",
      buildingNumber: "6",
      streetName: "يوسف وهبى",
      floorNumber: "2",
      flatNumber: "11",
      MobilePhone: "01201889278",
      HomePhone: "25902268",
      birthDate: "37631",
      fatherOfConfession: "أبونا يوسف",
      servantFollowing: "",
      chomosya: "شماس",
      school: "العابدية",
      facebook: "Mina Emad",
      email: "",
      fatherPhone: "1001449800",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "3",
      class: "2",
      zone: "A",
      name: "كيرلس رفيق راتب",
      buildingNumber: "17",
      streetName: "غالى",
      floorNumber: "2",
      flatNumber: "11",
      MobilePhone: "01288646506",
      HomePhone: "25975772",
      birthDate: "36850",
      fatherOfConfession: "أبونا يوسف",
      servantFollowing: "",
      chomosya: "شماس",
      school: "دى لاسال",
      facebook: "Kouka Rafik",
      email: "",
      fatherPhone: "1270170112",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "4",
      class: "2",
      zone: "A",
      name: "ماركو حنا رياض",
      buildingNumber: "10ب",
      streetName: "الجميل",
      floorNumber: "2",
      flatNumber: "7",
      MobilePhone: "01283044105",
      HomePhone: "25928059",
      birthDate: "37448",
      fatherOfConfession: "أبونا انجيلوس",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "الفاروق عمر",
      facebook: "Marko Hana",
      email: "",
      fatherPhone: "",
      motherPhone: "01276933389",
      notes: "مكبر دماغه و مراوغ (عايز اهتمام)",
      lastupdate: "28-11-2025"
    },
    {
      counter: "5",
      class: "2",
      zone: "A",
      name: "براين أمير",
      buildingNumber: "19",
      streetName: "حارة نسب",
      floorNumber: "5",
      flatNumber: "امام السلم",
      MobilePhone: "01212261872",
      HomePhone: "",
      birthDate: "37091",
      fatherOfConfession: "أبونا انجيلوس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "6",
      class: "2",
      zone: "A",
      name: "مارسلينو ناجى نعيم",
      buildingNumber: "8ب",
      streetName: "الجميل ",
      floorNumber: "1",
      flatNumber: "يمين",
      MobilePhone: "01279716481",
      HomePhone: "27868581",
      birthDate: "37272",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "",
      chomosya: "شماس",
      school: "التوفيق لغات",
      facebook: "",
      email: "pricemarcillino@hotmail.com",
      fatherPhone: "01282525849",
      motherPhone: "",
      notes: "",
      lastupdate: "41985"
    },
    {
      counter: "7",
      class: "2",
      zone: "A",
      name: "اديب هانى اديب",
      buildingNumber: "63",
      streetName: "كامل صدقى",
      floorNumber: "5",
      flatNumber: "شمال",
      MobilePhone: "1207924033",
      HomePhone: "25937806",
      birthDate: "37023",
      fatherOfConfession: "ابونا انجبلوس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "القديس ميخائيل",
      facebook: "Adeb Hany",
      email: "",
      fatherPhone: "01005321707",
      motherPhone: "",
      notes: "محتاج يتشد عليه",
      lastupdate: "15-10-2016"
    },
    {
      counter: "8",
      class: "2",
      zone: "A",
      name: "ابرام ادوار صموئيل",
      buildingNumber: "23",
      streetName: "حبيب شلبى",
      floorNumber: "5",
      flatNumber: "24",
      MobilePhone: "01289351358",
      HomePhone: "25907919",
      birthDate: "37195",
      fatherOfConfession: "ابونا تادرس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "الجلاء ",
      facebook: "Pero E. Samuel",
      email: "peroe.sumel@yahoo.com",
      fatherPhone: "01227297236",
      motherPhone: "01211138711",
      notes: "والدته مبسوطة من اعدادى",
      lastupdate: "15-10-2016"
    },
    {
      counter: "9",
      class: "2",
      zone: "A",
      name: "بيتر ايهاب",
      buildingNumber: "4",
      streetName: "يوسف سليمان",
      floorNumber: "ارضى",
      flatNumber: "15",
      MobilePhone: "01155938845",
      HomePhone: "1210652336",
      birthDate: "37453",
      fatherOfConfession: "ابونا انجبلوس",
      servantFollowing: "",
      chomosya: "",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "10",
      class: "2",
      zone: "A",
      name: "مينا وجية شفيق",
      buildingNumber: "",
      streetName: "شبرا",
      floorNumber: "",
      flatNumber: "",
      MobilePhone: "01202262444",
      HomePhone: "25902203",
      birthDate: "37025",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "",
      chomosya: "شماس",
      school: "البطريركية",
      facebook: "Mina Waguih",
      email: "mina_wagih22@yahoo.com",
      fatherPhone: "01229406211",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "11",
      class: "2",
      zone: "A",
      name: "فيلوباتير ماجد",
      buildingNumber: "6",
      streetName: "ابن بركة",
      floorNumber: "9",
      flatNumber: "ش",
      MobilePhone: "01100392299",
      HomePhone: "25910918",
      birthDate: "37086",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "شماس",
      school: "المارونية",
      facebook: "Philopateer M. zaki",
      email: "",
      fatherPhone: "01005662061",
      motherPhone: "",
      notes: "مش بيجى كتير و بياناته ناقصة",
      lastupdate: "28-11-2035"
    },
    {
      counter: "12",
      class: "2",
      zone: "A",
      name: "فيلوباتير عصام",
      buildingNumber: "10",
      streetName: "يوسف سليمان",
      floorNumber: "2",
      flatNumber: "5",
      MobilePhone: "01206676807",
      HomePhone: "",
      birthDate: "37311",
      fatherOfConfession: "ابونا أنجيلوس",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "الفاروق عمر",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: "28-11-2058"
    },
    {
      counter: "13",
      class: "2",
      zone: "A",
      name: "مارك جورج اديب",
      buildingNumber: "21",
      streetName: "يوسف وهبى",
      floorNumber: "4",
      flatNumber: "11",
      MobilePhone: "01201208458",
      HomePhone: "25890249",
      birthDate: "37375",
      fatherOfConfession: "ابونا انجبلوس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "رمسيس الجديدة",
      facebook: "Mark George",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "مش بيجى كتير",
      lastupdate: "15-10-2016"
    },
    {
      counter: "14",
      class: "2",
      zone: "A",
      name: "علاء سمهان",
      buildingNumber: "7",
      streetName: "حارة بيير الحلوة",
      floorNumber: "1",
      flatNumber: "3",
      MobilePhone: "01227002932",
      HomePhone: "01227002932",
      birthDate: "20-9-2001",
      fatherOfConfession: "",
      servantFollowing: "أ.مينا ممدوح",
      chomosya: "",
      school: "تقى اللة حلمى",
      facebook: "",
      email: "",
      fatherPhone: "01284036811",
      motherPhone: "",
      notes: "",
      lastupdate: "28-11-2023"
    },
    {
      counter: "15",
      class: "2",
      zone: "A",
      name: "فادى يوسف نصحى",
      buildingNumber: "193",
      streetName: "رمسيس",
      floorNumber: "ارضى",
      flatNumber: "",
      MobilePhone: "01228057680",
      HomePhone: "25923672",
      birthDate: "37370",
      fatherOfConfession: "ابونا تادرس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "التوفيق",
      facebook: "",
      email: "",
      fatherPhone: "1287014014",
      motherPhone: "",
      notes: "",
      lastupdate: "28-11-2048"
    },
    {
      counter: "16",
      class: "2",
      zone: "A",
      name: "اندرو اشرف",
      buildingNumber: "7",
      streetName: "الجد ",
      floorNumber: "1",
      flatNumber: "وسط",
      MobilePhone: "01282858828",
      HomePhone: "25908778",
      birthDate: "36734",
      fatherOfConfession: "عايز أبونا يوسف",
      servantFollowing: "",
      chomosya: "شماس",
      school: "البطريركية",
      facebook: "Andrew Ashraf",
      email: "",
      fatherPhone: "01223814047",
      motherPhone: "",
      notes: "عايز يعترف عند أبونا يوسف",
      lastupdate: "15-10-2016"
    },
    {
      counter: "17",
      class: "2",
      zone: "B",
      name: "كيرلس صفوت ",
      buildingNumber: "23",
      streetName: "الجد",
      floorNumber: "1",
      flatNumber: "19",
      MobilePhone: "01224485505",
      HomePhone: "",
      birthDate: "37310",
      fatherOfConfession: "أبونا يوسف",
      servantFollowing: "",
      chomosya: "شماس",
      school: "صحارا",
      facebook: "Kiro Safwat",
      email: "",
      fatherPhone: "01227415242",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "18",
      class: "2",
      zone: "B",
      name: "رامى عادل صديق",
      buildingNumber: "3",
      streetName: "سكة الجميل",
      floorNumber: "4",
      flatNumber: "15",
      MobilePhone: "01284348854",
      HomePhone: "25921359",
      birthDate: "37261",
      fatherOfConfession: "أبونا انجيلوس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "الجلاء",
      facebook: "Ramy Adel",
      email: "",
      fatherPhone: "01001278850",
      motherPhone: "",
      notes: "لازم يتسكن عند اب اعتراف",
      lastupdate: "15-10-2016"
    },
    {
      counter: "19",
      class: "2",
      zone: "B",
      name: "باسم شريف",
      buildingNumber: "33",
      streetName: "الظاهر",
      floorNumber: "6",
      flatNumber: "شمال",
      MobilePhone: "01096969651",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "",
      school: "صحارا",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "جديد من العذراء الفجالة",
      lastupdate: ""
    },
    {
      counter: "20",
      class: "2",
      zone: "B",
      name: "كريم شريف عزت",
      buildingNumber: "33",
      streetName: "الظاهر",
      floorNumber: "1",
      flatNumber: "2",
      MobilePhone: "01225239038",
      HomePhone: "25903190",
      birthDate: "37092",
      fatherOfConfession: "ابونا أنجيلوس",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "دى لاسال",
      facebook: "",
      email: "",
      fatherPhone: "01225239038",
      motherPhone: "",
      notes: "",
      lastupdate: "21-12-2014"
    },
    {
      counter: "21",
      class: "2",
      zone: "B",
      name: "مارك ماجد لبيب",
      buildingNumber: "3",
      streetName: "بستان التاج",
      floorNumber: "2",
      flatNumber: "5",
      MobilePhone: "01281735519",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "",
      school: "الجلاء",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "جديد اول مرة (الشقة اللى على السلم)",
      lastupdate: ""
    },
    {
      counter: "22",
      class: "2",
      zone: "B",
      name: "كيرلس ملاك عوض",
      buildingNumber: "32أ",
      streetName: "الجد",
      floorNumber: "2",
      flatNumber: "ى",
      MobilePhone: "01224043945",
      HomePhone: "27867413",
      birthDate: "37002",
      fatherOfConfession: "ابونا فيلوباتير (الفجالة)",
      servantFollowing: "",
      chomosya: "",
      school: "التوفيق",
      facebook: "",
      email: "",
      fatherPhone: "01225219795",
      motherPhone: "01224043945",
      notes: "",
      lastupdate: "28-11-2067"
    },
    {
      counter: "23",
      class: "2",
      zone: "B",
      name: "مايكل هانى كريم",
      buildingNumber: "23",
      streetName: "الجد",
      floorNumber: "2",
      flatNumber: "29",
      MobilePhone: "01212241146",
      HomePhone: "25882130",
      birthDate: "37287",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "",
      chomosya: "شماس",
      school: "صحارا",
      facebook: "Michael Hany",
      email: "",
      fatherPhone: "01220436640",
      motherPhone: "",
      notes: "نتأكد ان عنده اب اعتراف",
      lastupdate: "41985"
    },
    {
      counter: "24",
      class: "2",
      zone: "B",
      name: "ابانوب علاء نادى",
      buildingNumber: "32ب",
      streetName: "الجد",
      floorNumber: "3",
      flatNumber: "ى",
      MobilePhone: "01211350352",
      HomePhone: "27860578",
      birthDate: "37438",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "شماس",
      school: "التوفيق",
      facebook: "",
      email: "",
      fatherPhone: "01223631317",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "25",
      class: "2",
      zone: "B",
      name: "جورج اشرف منير",
      buildingNumber: "28",
      streetName: "بركة الرطل",
      floorNumber: "1",
      flatNumber: "ي",
      MobilePhone: "01201676614",
      HomePhone: "25883981",
      birthDate: "37418",
      fatherOfConfession: "أبونا أنجيلوس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "دى لاسال",
      facebook: "George Ashraf",
      email: "",
      fatherPhone: "01289042590",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "26",
      class: "2",
      zone: "B",
      name: "جورج رافت وليم",
      buildingNumber: "3أ",
      streetName: "السبع",
      floorNumber: "1",
      flatNumber: "5",
      MobilePhone: "01224868690",
      HomePhone: "25930663",
      birthDate: "27/9/2001",
      fatherOfConfession: "ابونا أنجيلوس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "صحارا",
      facebook: "Gogo Rafaat",
      email: "",
      fatherPhone: "01224868690",
      motherPhone: "",
      notes: "نتأكد من عيد ميلاده",
      lastupdate: "15-10-2016"
    },
    {
      counter: "27",
      class: "2",
      zone: "B",
      name: "كيرلس هشام ",
      buildingNumber: "4",
      streetName: "حمدى",
      floorNumber: "4",
      flatNumber: "19",
      MobilePhone: "01288072671",
      HomePhone: "25922515",
      birthDate: "37611",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "",
      chomosya: "شماس",
      school: "القديس ميخائيل",
      facebook: "Kiro Hesham",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "محتاج يجى بالزن",
      lastupdate: "28-11-2055"
    },
    {
      counter: "28",
      class: "2",
      zone: "C",
      name: "مارتن ميلاد نصحى",
      buildingNumber: "12",
      streetName: "ذكى",
      floorNumber: "3",
      flatNumber: "3",
      MobilePhone: "01283911916",
      HomePhone: "25903683",
      birthDate: "36949",
      fatherOfConfession: "ابونا انجبلوس",
      servantFollowing: "",
      chomosya: "-",
      school: "المارونية",
      facebook: "",
      email: "",
      fatherPhone: "01220602238",
      motherPhone: "",
      notes: "",
      lastupdate: "28-11-2041"
    },
    {
      counter: "29",
      class: "2",
      zone: "C",
      name: "يوسف هانى نصحى",
      buildingNumber: "12",
      streetName: "ذكى",
      floorNumber: "1",
      flatNumber: "1",
      MobilePhone: "01229970370",
      HomePhone: "25887811",
      birthDate: "37139",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "المارونية",
      facebook: "",
      email: "",
      fatherPhone: "01227191247",
      motherPhone: "",
      notes: "",
      lastupdate: "28-11-2042"
    },
    {
      counter: "30",
      class: "2",
      zone: "C",
      name: "كيرلس وجدى زكى",
      buildingNumber: "1",
      streetName: "ش مراد",
      floorNumber: "2",
      flatNumber: "206",
      MobilePhone: "01225638892",
      HomePhone: "",
      birthDate: "37264",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "المارونية",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "31",
      class: "2",
      zone: "C",
      name: "مايكل سميح",
      buildingNumber: "42",
      streetName: "حمدى",
      floorNumber: "1",
      flatNumber: "13",
      MobilePhone: "01228944451",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "",
      school: "دى لاسال",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "تكملة بياناته",
      lastupdate: "21-10-2016"
    },
    {
      counter: "32",
      class: "2",
      zone: "C",
      name: "بافلى شريف",
      buildingNumber: "22أ",
      streetName: "ادريس راغب",
      floorNumber: "1",
      flatNumber: "1",
      MobilePhone: "01279878716",
      HomePhone: "",
      birthDate: "37358",
      fatherOfConfession: "ابونا موسى",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "المارونية",
      facebook: "Pavly Sherif",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "33",
      class: "2",
      zone: "C",
      name: "يوسف خلف",
      buildingNumber: "22",
      streetName: "شارع ادريس راغب",
      floorNumber: "3",
      flatNumber: "12",
      MobilePhone: "01124585149",
      HomePhone: "25886027",
      birthDate: "37548",
      fatherOfConfession: "عايز أبونا أنجيلوس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "القديس ميخائيل",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "محتاج بياناته تتكمل",
      lastupdate: "42064"
    },
    {
      counter: "34",
      class: "2",
      zone: "C",
      name: "امير ايهاب عزمى",
      buildingNumber: "22",
      streetName: "ذهنى",
      floorNumber: "أرضى",
      flatNumber: "1",
      MobilePhone: "01153057232",
      HomePhone: "25934591",
      birthDate: "37340",
      fatherOfConfession: "أبونا أنجيلوس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "صحارا",
      facebook: "Amir Ehab Azmy",
      email: "",
      fatherPhone: "01220310669",
      motherPhone: "",
      notes: "نعرف مين اب اعترافه",
      lastupdate: "41985"
    },
    {
      counter: "35",
      class: "2",
      zone: "C",
      name: "فادى فريد محفوظ",
      buildingNumber: "42",
      streetName: "حمدى",
      floorNumber: "8",
      flatNumber: "83",
      MobilePhone: "01280994626",
      HomePhone: "25894968",
      birthDate: "37538",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "",
      chomosya: "شماس",
      school: "الجلاء",
      facebook: "Fady El kess Aghnatious",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "36",
      class: "2",
      zone: "C",
      name: "جون مجدى",
      buildingNumber: "22",
      streetName: "ذهنى",
      floorNumber: "6",
      flatNumber: "21",
      MobilePhone: "01027725520",
      HomePhone: "",
      birthDate: "37241",
      fatherOfConfession: "أبونا أنجيلوس",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "تقى الله حلمى",
      facebook: "John Magdy",
      email: "",
      fatherPhone: "01282501983",
      motherPhone: "",
      notes: "نتأكد منلبيانات + نقم الموبيل",
      lastupdate: "28-11-2045"
    },
    {
      counter: "37",
      class: "2",
      zone: "C",
      name: "بيشوى حنا ميخائيل",
      buildingNumber: "73",
      streetName: "القبيسى",
      floorNumber: "5",
      flatNumber: "10",
      MobilePhone: "01276685078",
      HomePhone: "__",
      birthDate: "37441",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "",
      chomosya: "شماس",
      school: "القديس ميخائيل",
      facebook: "Beshoy Hanna",
      email: "",
      fatherPhone: "1223368288",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "38",
      class: "2",
      zone: "C",
      name: "بافلى جرجس بطرس",
      buildingNumber: "86",
      streetName: "القبيسى",
      floorNumber: "6",
      flatNumber: "11",
      MobilePhone: "01277750998",
      HomePhone: "25889735",
      birthDate: "26/11/2000",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "ثمرة التوفيق ",
      facebook: "Be KO Oo",
      email: "",
      fatherPhone: "1224362101",
      motherPhone: "",
      notes: "مش بيجى كتير و لازم يتسكن عند اب اعتراف ضرورى",
      lastupdate: "15-10-2016"
    },
    {
      counter: "39",
      class: "2",
      zone: "C",
      name: "مينا خالد",
      buildingNumber: "5",
      streetName: "ح سراج(ش مراد)",
      floorNumber: "ارضى",
      flatNumber: "ش",
      MobilePhone: "ـــــــــ",
      HomePhone: "ـــــــــ",
      birthDate: "37476",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "تقى اللة حلمى",
      facebook: "",
      email: "",
      fatherPhone: "01225868614",
      motherPhone: "01115432763",
      notes: "اخوة رب",
      lastupdate: "15-10-2016"
    },
    {
      counter: "40",
      class: "2",
      zone: "C",
      name: "بافلى ايهاب",
      buildingNumber: "33",
      streetName: "ذهنى",
      floorNumber: "3",
      flatNumber: "11",
      MobilePhone: "01289899393",
      HomePhone: "25939695",
      birthDate: "37257",
      fatherOfConfession: "ابونا برسوم",
      servantFollowing: "",
      chomosya: "شماس",
      school: "القديس ميخائيل",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: "28-11-2047"
    },
    {
      counter: "41",
      class: "2",
      zone: "C",
      name: "جورج هانى حنا",
      buildingNumber: "207",
      streetName: "رمسيس",
      floorNumber: "6",
      flatNumber: "601",
      MobilePhone: "01203192632",
      HomePhone: "25896965",
      birthDate: "37561",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "",
      chomosya: "شماس",
      school: "بطمس",
      facebook: "Gero Hany",
      email: "",
      fatherPhone: "1223423986",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "42",
      class: "2",
      zone: "C",
      name: "مايكل ميلاد",
      buildingNumber: "16",
      streetName: "ح عبد المجيد محمد-ميدان فخرى",
      floorNumber: "قبل الأخير",
      flatNumber: "شمال",
      MobilePhone: "01289359894",
      HomePhone: "",
      birthDate: "37508",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "01203690415",
      notes: "",
      lastupdate: "28-11-2081"
    },
    {
      counter: "43",
      class: "2",
      zone: "C",
      name: "مكارى ابراهيم",
      buildingNumber: "11",
      streetName: "المهرانى",
      floorNumber: "ارضى",
      flatNumber: "",
      MobilePhone: "",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "44",
      class: "2",
      zone: "C",
      name: "ابانوب عزت",
      buildingNumber: "22أ",
      streetName: "حارة ابن الغنام (ميدان فخرى)",
      floorNumber: "الثانى",
      flatNumber: "يمين",
      MobilePhone: "01117061033",
      HomePhone: "ــــــــ",
      birthDate: "37240",
      fatherOfConfession: "أبونا أنجيلوس",
      servantFollowing: "",
      chomosya: "",
      school: "ثمرة التوفيق ",
      facebook: "",
      email: "",
      fatherPhone: "ــــــــ",
      motherPhone: "",
      notes: "",
      lastupdate: "41985"
    },
    {
      counter: "45",
      class: "2",
      zone: "D",
      name: "كيرلس جوزيف",
      buildingNumber: "5",
      streetName: "ميدان الظاهر",
      floorNumber: "7",
      flatNumber: "705",
      MobilePhone: "01063377003",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "46",
      class: "2",
      zone: "D",
      name: "ماركو ميخائيل",
      buildingNumber: "9",
      streetName: "صبرى",
      floorNumber: "3",
      flatNumber: "14",
      MobilePhone: "01226707175",
      HomePhone: "27877622",
      birthDate: "37274",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "",
      chomosya: "",
      school: "الجلاء",
      facebook: "Arco Marco",
      email: "",
      fatherPhone: "01278297976",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "47",
      class: "2",
      zone: "D",
      name: "جورج حسنى",
      buildingNumber: "11",
      streetName: "صبرى",
      floorNumber: "3",
      flatNumber: "سلم",
      MobilePhone: "01129455807",
      HomePhone: "25880178",
      birthDate: "29/9/2001",
      fatherOfConfession: "أبونا بيشوى وهبة",
      servantFollowing: "",
      chomosya: "شماس",
      school: "نيو رمسيس",
      facebook: "",
      email: "",
      fatherPhone: "01272047775",
      motherPhone: "",
      notes: "ملتزم مع ابونا بيشوى وهبة ",
      lastupdate: "41985"
    },
    {
      counter: "48",
      class: "2",
      zone: "D",
      name: "مينا سامح خليل",
      buildingNumber: "6",
      streetName: "ادريس راغب",
      floorNumber: "8",
      flatNumber: "24",
      MobilePhone: "01288874638",
      HomePhone: "25918629",
      birthDate: "37340",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "",
      chomosya: "شماس",
      school: "المارونية",
      facebook: "Mina Sameh",
      email: "",
      fatherPhone: "01221756534",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "49",
      class: "2",
      zone: "D",
      name: "ماريو زكي",
      buildingNumber: "29",
      streetName: "صبرى",
      floorNumber: "8",
      flatNumber: "16",
      MobilePhone: "01206476525",
      HomePhone: "25932957",
      birthDate: "37686",
      fatherOfConfession: "أبونا دانيال (الملاك حارة السقايين)",
      servantFollowing: "",
      chomosya: "شماس",
      school: "السلام",
      facebook: "Mario zaki",
      email: "",
      fatherPhone: "",
      motherPhone: "01284811748",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "50",
      class: "2",
      zone: "D",
      name: "عادل نادر",
      buildingNumber: "65",
      streetName: "الظاهر",
      floorNumber: "3",
      flatNumber: "10",
      MobilePhone: "01222220572",
      HomePhone: "__",
      birthDate: "37294",
      fatherOfConfession: "أبونا يوسف",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "دى لاسال",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "فوق مونجينى",
      lastupdate: "15-10-2016"
    },
    {
      counter: "51",
      class: "2",
      zone: "D",
      name: "ريمون نادر",
      buildingNumber: "64",
      streetName: "الظاهر",
      floorNumber: "8",
      flatNumber: "30",
      MobilePhone: "01281586603",
      HomePhone: "25901839",
      birthDate: "37246",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "نيو رمسيس",
      facebook: "Remon Nader",
      email: "",
      fatherPhone: "01281586603",
      motherPhone: "",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "52",
      class: "2",
      zone: "D",
      name: "موسى صبحى",
      buildingNumber: "2",
      streetName: "ذهنى",
      floorNumber: "ارضى",
      flatNumber: "",
      MobilePhone: "01272171161",
      HomePhone: "__",
      birthDate: "37485",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "الفاروق عمر",
      facebook: "",
      email: "",
      fatherPhone: "1115782647",
      motherPhone: "01275518473",
      notes: "",
      lastupdate: "15-10-2016"
    },
    {
      counter: "53",
      class: "2",
      zone: "D",
      name: "جون مجدى شفيق",
      buildingNumber: "9",
      streetName: "شارع ذهنى",
      floorNumber: "1",
      flatNumber: "3",
      MobilePhone: "01100551743",
      HomePhone: "25897110",
      birthDate: "37226",
      fatherOfConfession: "عايز ابونا أنجيلوس",
      servantFollowing: "",
      chomosya: "شماس",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "نتأكد من البيانات + رقم الموبيل",
      lastupdate: "28-11-2081"
    },
    {
      counter: "54",
      class: "2",
      zone: "D",
      name: "شريف خلف",
      buildingNumber: "4",
      streetName: "ش درويش (متفرع من ذهنى)",
      floorNumber: "4",
      flatNumber: "3 (حمراء)",
      MobilePhone: "01221445766",
      HomePhone: "",
      birthDate: "37204",
      fatherOfConfession: "ابونا رافائيل",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "مدرسة السلام عند كوبرى غمرة",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "01280300307",
      notes: "",
      lastupdate: "42494"
    },
    {
      counter: "55",
      class: "2",
      zone: "D",
      name: "ماريو ناجي نصيف",
      buildingNumber: "39",
      streetName: "حارة الشرابية",
      floorNumber: "2",
      flatNumber: "2",
      MobilePhone: "01227300553",
      HomePhone: "22354970",
      birthDate: "37481",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "",
      chomosya: "-",
      school: "الجلاء التجريبية لغات",
      facebook: "Mario Nagy",
      email: "marionagy2002@yahoo.com",
      fatherPhone: "",
      motherPhone: "01226837311",
      notes: "أمام فرن عيش",
      lastupdate: "28-11-2079"
    },
    {
      counter: "56",
      class: "2",
      zone: "D",
      name: "جرجس نادى رؤوف ",
      buildingNumber: "2",
      streetName: "خليج الطواب",
      floorNumber: "3",
      flatNumber: "6",
      MobilePhone: "01220013205",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "أبونا أنجيلوس",
      servantFollowing: "",
      chomosya: "",
      school: "القديس ميخائيل",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "57",
      class: "2",
      zone: "D",
      name: "اميل صفوت",
      buildingNumber: "3",
      streetName: "ادريس راغب",
      floorNumber: "الاخير",
      flatNumber: "",
      MobilePhone: "01278024416",
      HomePhone: "____",
      birthDate: "28/2/2002",
      fatherOfConfession: "ابونا روفائيل (المنسى)",
      servantFollowing: "",
      chomosya: "شماس",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "اخوة رب",
      lastupdate: ""
    },
    {
      counter: "58",
      class: "2",
      zone: "D",
      name: "انطون وائل",
      buildingNumber: "54",
      streetName: "عبد الحميد الديب - الخلفاوى",
      floorNumber: "6",
      flatNumber: "11",
      MobilePhone: "01202805680",
      HomePhone: "",
      birthDate: "19/6/2002",
      fatherOfConfession: "ابونا رويس ( العدرا و الملاك الخلفاوى)",
      servantFollowing: "",
      chomosya: "شماس",
      school: "طارق بن زياد",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "جديد",
      lastupdate: ""
    },
    {
      counter: "59",
      class: "2",
      zone: "D",
      name: "مارتن ايهاب",
      buildingNumber: "",
      streetName: "الحى الاول - محلية 5 - العبور",
      floorNumber: "",
      flatNumber: "",
      MobilePhone: "-------",
      HomePhone: "",
      birthDate: "25/8/2002",
      fatherOfConfession: "لا يوجد ",
      servantFollowing: "",
      chomosya: "غير شماس",
      school: "الفا - العبور",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "01200050549",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "60",
      class: "2",
      zone: "D",
      name: "تونى نسيم",
      buildingNumber: "3",
      streetName: "حارة المبلاط - الشرابية",
      floorNumber: "1",
      flatNumber: "1",
      MobilePhone: "01226550950",
      HomePhone: "------",
      birthDate: "",
      fatherOfConfession: "ابونا يوسف (الزاوية)",
      servantFollowing: "",
      chomosya: "",
      school: "السلام",
      facebook: "",
      email: "",
      fatherPhone: "01205572457",
      motherPhone: "",
      notes: "جديد من كنيسة العذراء الزاوية",
      lastupdate: ""
    },
    {
      counter: "61",
      class: "2",
      zone: "D",
      name: "بيشوى إدوار",
      buildingNumber: "5",
      streetName: "ش ذهنى",
      floorNumber: "4",
      flatNumber: "14",
      MobilePhone: "01201493556",
      HomePhone: "25914416",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "62",
      class: "2",
      zone: "D",
      name: "بيتر أشرف",
      buildingNumber: "4",
      streetName: "حارة العجمى (متفرع من حمدى)",
      floorNumber: "5",
      flatNumber: "9",
      MobilePhone: "",
      HomePhone: "25888748",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "63",
      class: "2",
      zone: "D",
      name: "كيرلس عماد",
      buildingNumber: "",
      streetName: "",
      floorNumber: "",
      flatNumber: "",
      MobilePhone: "",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "64",
      class: "2",
      zone: "D",
      name: "سمعان مجدي",
      buildingNumber: "",
      streetName: "المرج"
    },
    {
      counter: "1",
      class: "3",
      zone: "A",
      name: "يـوسف مدحـت فــــرج ",
      buildingNumber: "5",
      streetName: "شارع الجد",
      floorNumber: "2",
      flatNumber: "10",
      MobilePhone: "01203702499",
      HomePhone: "27879256",
      birthDate: "36833",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "أ. بيشوى",
      chomosya: "ابصالتس",
      school: "القديس ميخائيل",
      facebook: "youssef Medhat ",
      email: "",
      fatherPhone: "1229361392",
      motherPhone: "01207250271",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "2",
      class: "3",
      zone: "A",
      name: "رؤوف عزيز كمــال",
      buildingNumber: "32",
      streetName: "شارع الجد",
      floorNumber: "4",
      flatNumber: "-",
      MobilePhone: "01210770402",
      HomePhone: "25887998",
      birthDate: "37198",
      fatherOfConfession: "ابونا برسوم",
      servantFollowing: "أ. بيشوى",
      chomosya: "ابصالتس",
      school: "القديس ميخائيل",
      facebook: "Raouf Aziz ",
      email: "raoufaziz88@gmail.com",
      fatherPhone: "1222225417",
      motherPhone: "01202225127",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "3",
      class: "3",
      zone: "A",
      name: "رويس رضـا انـدراوس",
      buildingNumber: "21",
      streetName: "شارع يوسف وهبي",
      floorNumber: "9",
      flatNumber: "40",
      MobilePhone: "01284668695",
      HomePhone: "27864564",
      birthDate: "36540",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. مينا نادى",
      chomosya: "ابصالتس",
      school: "البطريركية",
      facebook: "Rowace R. Andraws",
      email: "rowacereda@hotmail.com",
      fatherPhone: "",
      motherPhone: "1205993995",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "4",
      class: "3",
      zone: "A",
      name: "كيرلس نشــات حنا",
      buildingNumber: "25",
      streetName: "شارع الجميل",
      floorNumber: "1",
      flatNumber: "1 ى ",
      MobilePhone: "01023211556",
      HomePhone: "25886615",
      birthDate: "36809",
      fatherOfConfession: "ابونا تادرس",
      servantFollowing: "أ. بيشوى",
      chomosya: "ابصالتس",
      school: "صحارة للغات",
      facebook: "Kirolous Nashaat ",
      email: "kirolouss@gmail.com",
      fatherPhone: "1227003932",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "5",
      class: "3",
      zone: "A",
      name: "جـــورج منـير عــريان",
      buildingNumber: "4",
      streetName: "شارع ابن بركة",
      floorNumber: "4",
      flatNumber: "18",
      MobilePhone: "01201290550/01281810903",
      HomePhone: "25884710",
      birthDate: "36959",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. بيتر ",
      chomosya: "ابصالتس",
      school: "صحارة للغات",
      facebook: "George Mounir ",
      email: "george_2222@hotmail.com",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "6",
      class: "3",
      zone: "A",
      name: "مايكل جرجس أنيــس",
      buildingNumber: "4",
      streetName: "سكة الجميل",
      floorNumber: "5",
      flatNumber: "18",
      MobilePhone: "01200943892",
      HomePhone: "2786879",
      birthDate: "36987",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. بيشوى",
      chomosya: "ابصالتس",
      school: "القديس ميخائيل",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "7",
      class: "3",
      zone: "A",
      name: "جورج ميشيل ميخائيل",
      buildingNumber: "23",
      streetName: "شارع غالي",
      floorNumber: "6",
      flatNumber: "17ش",
      MobilePhone: "01227648734",
      HomePhone: "لا يوجد",
      birthDate: "22/10/2000",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. إبراهيم",
      chomosya: "ابصالتس",
      school: "عاطف صدقى التجريبية مصر الجديدة",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "8",
      class: "3",
      zone: "A",
      name: "جـورج اسحـاق دميــان",
      buildingNumber: "15",
      streetName: "شارع غالي",
      floorNumber: "3",
      flatNumber: "10",
      MobilePhone: "01226695635",
      HomePhone: "25890893",
      birthDate: "37170",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "أ. إبراهيم",
      chomosya: "ابصالتس",
      school: "الراعى الصالح",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "9",
      class: "3",
      zone: "A",
      name: "باسم اشرف ( أيمن يوسف )",
      buildingNumber: "7",
      streetName: "شارع غالي",
      floorNumber: "ارضي",
      flatNumber: "",
      MobilePhone: "01279714297",
      HomePhone: "25904997",
      birthDate: "36563",
      fatherOfConfession: "ابونا برسوم",
      servantFollowing: "أ. مينا نادى",
      chomosya: "غير مرشوم ",
      school: "النظام",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "الملجأ",
      lastupdate: "42673"
    },
    {
      counter: "10",
      class: "3",
      zone: "A",
      name: "مــارك ايهــاب شكــرى",
      buildingNumber: "17",
      streetName: "شارع يوسف سليمان",
      floorNumber: "1",
      flatNumber: "3",
      MobilePhone: "01203921518",
      HomePhone: "25916841",
      birthDate: "36873",
      fatherOfConfession: "ابونا برسوم",
      servantFollowing: "أ. بيتر ",
      chomosya: "ابصالتس",
      school: "صحارة للغات",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: "41945"
    },
    {
      counter: "11",
      class: "3",
      zone: "A",
      name: "ابانوب كامل",
      buildingNumber: "",
      streetName: "عمارة كيرومينا",
      floorNumber: "الأرضى",
      flatNumber: "-",
      MobilePhone: "01127635970",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. مينا نادى",
      chomosya: "",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "12",
      class: "3",
      zone: "B",
      name: "يوســف مكـــرم نصــر",
      buildingNumber: "8",
      streetName: "حارة ابا الحارث",
      floorNumber: "4",
      flatNumber: "ي",
      MobilePhone: "01201863730",
      HomePhone: "27877844",
      birthDate: "36829",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "أ. مينا نادى",
      chomosya: "غير مرشوم ",
      school: "الفاروق عمر",
      facebook: "Youssef Joo",
      email: "",
      fatherPhone: "",
      motherPhone: "1224797554",
      notes: "الاب متوفى - حالة خاصة",
      lastupdate: ""
    },
    {
      counter: "13",
      class: "3",
      zone: "B",
      name: "باســم شكــرى يــوسف",
      buildingNumber: "19",
      streetName: "حارة نسب",
      floorNumber: "10",
      flatNumber: "24",
      MobilePhone: "01279006897",
      HomePhone: "25920602",
      birthDate: "37076",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "أ. إبراهيم",
      chomosya: "ابصالتس",
      school: "القديس ميخائيل",
      facebook: "Beso Shokry ",
      email: "shokry.youssef@yahoo.com",
      fatherPhone: "1223627810",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "14",
      class: "3",
      zone: "B",
      name: "جــورج بــاســم كـامـل",
      buildingNumber: "13",
      streetName: "يوسف سليمان",
      floorNumber: "3",
      flatNumber: "10",
      MobilePhone: "01159477925",
      HomePhone: "",
      birthDate: "20/10/2001",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. إبراهيم",
      chomosya: "ابصالتس",
      school: "مصر 2000 التجمع الخامس",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: "41945"
    },
    {
      counter: "15",
      class: "3",
      zone: "B",
      name: "مكسيموس مدحت مفـــيد",
      buildingNumber: "4",
      streetName: "ببطرس غالى ",
      floorNumber: "3",
      flatNumber: "5",
      MobilePhone: "01279457242",
      HomePhone: "25931195",
      birthDate: "37040",
      fatherOfConfession: "ابونا موسى",
      servantFollowing: "أ. بيتر ",
      chomosya: "ابصالتس",
      school: "صحارة للغات",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: "41945"
    },
    {
      counter: "16",
      class: "3",
      zone: "B",
      name: "صموئيل نصحي حبيب",
      buildingNumber: "16",
      streetName: "شارع بركة الرطل",
      floorNumber: "6",
      flatNumber: "22ش",
      MobilePhone: "01226715009",
      HomePhone: "25909056",
      birthDate: "37141",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. مينا نادى",
      chomosya: "ابصالتس",
      school: "التوفيق",
      facebook: "Samuel Noshy ",
      email: "samuel88@yahoo.com",
      fatherPhone: "1223340604",
      motherPhone: "01220670690",
      notes: "",
      lastupdate: "41945"
    },
    {
      counter: "17",
      class: "3",
      zone: "B",
      name: "ابـانوب اسـامة سمير",
      buildingNumber: "10",
      streetName: "حارة بستان التاج",
      floorNumber: "1",
      flatNumber: "2",
      MobilePhone: "01202675985",
      HomePhone: "25889046",
      birthDate: "37030",
      fatherOfConfession: "ابونا برسوم",
      servantFollowing: "أ. بيتر ",
      chomosya: "ابصالتس",
      school: "القديس ميخائيل",
      facebook: "Bibo.Abanob osama ",
      email: "",
      fatherPhone: "1227555042",
      motherPhone: "",
      notes: "",
      lastupdate: "41945"
    },
    {
      counter: "18",
      class: "3",
      zone: "B",
      name: "فيلوبتير مخلص يونان",
      buildingNumber: "3",
      streetName: "سكة البشنيني",
      floorNumber: "8",
      flatNumber: "16",
      MobilePhone: "01226444896",
      HomePhone: "25913916",
      birthDate: "36838",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. بيشوى",
      chomosya: "ابصالتس",
      school: "نيو رمسيس ",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: "42673"
    },
    {
      counter: "19",
      class: "3",
      zone: "B",
      name: "يوسف سعد لطفى",
      buildingNumber: "3",
      streetName: "بستان التاج",
      floorNumber: "2",
      flatNumber: "6",
      MobilePhone: "01279122664",
      HomePhone: "",
      birthDate: "36741",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. إبراهيم",
      chomosya: "ابصالتس",
      school: "بطريركية",
      facebook: "youssef saad ",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "تأخر دراسى",
      lastupdate: "42015"
    },
    {
      counter: "20",
      class: "3",
      zone: "B",
      name: "كيرلس روماني سليمان",
      buildingNumber: "67",
      streetName: "شارع كامل صدقي ",
      floorNumber: "8",
      flatNumber: "704",
      MobilePhone: "01280926434",
      HomePhone: "25880822",
      birthDate: "36531",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. بيشوى",
      chomosya: "ابصالتس",
      school: "النصر التجريبية ميدان الجيش",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "21",
      class: "3",
      zone: "B",
      name: "ايـلي جــورج ناصـوح",
      buildingNumber: "2",
      streetName: "ميدان بركة الرطل",
      floorNumber: "9",
      flatNumber: "26",
      MobilePhone: "01061811042",
      HomePhone: "27872290",
      birthDate: "36702",
      fatherOfConfession: "ابونا موسي نيروز",
      servantFollowing: "أ. إبراهيم",
      chomosya: "ابصالتس",
      school: "الدى لاسال",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "22",
      class: "3",
      zone: "B",
      name: "مايكـل عصـام عـريــان",
      buildingNumber: "25",
      streetName: "شارع حبيب شلبي",
      floorNumber: "6",
      flatNumber: "2",
      MobilePhone: "01286044974",
      HomePhone: "25922593",
      birthDate: "36762",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. إبراهيم",
      chomosya: "ابصالتس",
      school: "البطريركية",
      facebook: "",
      email: "",
      fatherPhone: "1226483303",
      motherPhone: "1227867656",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "23",
      class: "3",
      zone: "C",
      name: "ابانوب ميخائيل",
      buildingNumber: "75",
      streetName: "القبيسي ( العمارة اللي في الوسط )",
      floorNumber: "4",
      flatNumber: "21",
      MobilePhone: "01204314087",
      HomePhone: "25894753",
      birthDate: "36863",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "أ. بيتر ",
      chomosya: "",
      school: "اسماعيل القبانى",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "012206600269",
      notes: "عنده كشافة فى ميعاد الخدمة - السريان ",
      lastupdate: "15-11-2016"
    },
    {
      counter: "24",
      class: "3",
      zone: "C",
      name: "جيوفاني انطون بشرى",
      buildingNumber: "22ب",
      streetName: "شارع صبري",
      floorNumber: "4",
      flatNumber: "13",
      MobilePhone: "01277950043",
      HomePhone: "25901960",
      birthDate: "36974",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. بيتر ",
      chomosya: "ابصالتس",
      school: "القديس ميخائيل",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "عنده درس الساعة 6:30",
      lastupdate: "42301"
    },
    {
      counter: "25",
      class: "3",
      zone: "C",
      name: "يوسف مجدى موريس ",
      buildingNumber: "15",
      streetName: "شارع ذهنى",
      floorNumber: "2",
      flatNumber: "4",
      MobilePhone: "01006456732",
      HomePhone: "27873613",
      birthDate: "",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. بيشوى",
      chomosya: "",
      school: "القديس ميخائيل",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: "41945"
    },
    {
      counter: "26",
      class: "3",
      zone: "C",
      name: "بيتــر اشــرف صـــليب",
      buildingNumber: "4",
      streetName: "حارة العرقبجى بجوار تبارك",
      floorNumber: "5",
      flatNumber: "9",
      MobilePhone: "01123051651",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "أ. بيتر ",
      chomosya: "",
      school: "القديس ميخائيل",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "بيروح كشافة السريان",
      lastupdate: "42673"
    },
    {
      counter: "27",
      class: "3",
      zone: "C",
      name: "شــادي ايهـــاب زكـريا",
      buildingNumber: "13أ",
      streetName: "شارع مراد",
      floorNumber: "1",
      flatNumber: "وش",
      MobilePhone: "01013804996",
      HomePhone: "27878879",
      birthDate: "37070",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. بيشوى",
      chomosya: "",
      school: "المبتديان",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "السريان ",
      lastupdate: "42673"
    },
    {
      counter: "28",
      class: "3",
      zone: "C",
      name: "رضا ملاك",
      buildingNumber: "4",
      streetName: "شارع حمدي",
      floorNumber: "ارضي",
      flatNumber: "-",
      MobilePhone: "01124513257",
      HomePhone: "",
      birthDate: "36988",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. مينا نادى",
      chomosya: "لا",
      school: "السيدة - السلام",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "29",
      class: "3",
      zone: "C",
      name: "جورج عادل جورج",
      buildingNumber: "18",
      streetName: "شارع ارض الامامين",
      floorNumber: "2",
      flatNumber: "2",
      MobilePhone: "01283367491",
      HomePhone: "",
      birthDate: "37031",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "أ. بيشوى",
      chomosya: "ابصالتس",
      school: "اسماعيل القبانى",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "01227242786",
      notes: "قاعد معظم الوقت فى عمارة الجمعية الدور الأخير. (جدته)",
      lastupdate: "42673"
    },
    {
      counter: "30",
      class: "3",
      zone: "C",
      name: "ميلاد استمالك",
      buildingNumber: "23",
      streetName: "شارع الظاهر",
      floorNumber: "ارضي",
      flatNumber: "",
      MobilePhone: "01157283364",
      HomePhone: "",
      birthDate: "36527",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "أ. مينا نادى",
      chomosya: "ابصالتس",
      school: "الراعى الصالح",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "والده متوفى - سجائر - عاملين - تأخر دراسى",
      lastupdate: "42673"
    },
    {
      counter: "31",
      class: "3",
      zone: "C",
      name: "انتوني جرجس منقاريوس",
      buildingNumber: "49",
      streetName: "القبيسي",
      floorNumber: "7",
      flatNumber: "7",
      MobilePhone: "01272634063",
      HomePhone: "25883224",
      birthDate: "37332",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. بيتر ",
      chomosya: "ابصالتس",
      school: "المارونية",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "32",
      class: "3",
      zone: "C",
      name: "اندرو ادورد",
      buildingNumber: "15",
      streetName: "ذهني",
      floorNumber: "3",
      flatNumber: "5",
      MobilePhone: "01287261046",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "ابونا يوسف",
      servantFollowing: "أ. بيشوى",
      chomosya: "ابصالتس",
      school: "غمرة ثانوية بنين",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "01201039747",
      notes: "",
      lastupdate: "42673"
    },
    {
      counter: "33",
      class: "3",
      zone: "C",
      name: "فــادي جمـيل سعــد",
      buildingNumber: "24",
      streetName: "شارع القبيسي",
      floorNumber: "5",
      flatNumber: "5",
      MobilePhone: "01202985651",
      HomePhone: "25924330",
      birthDate: "36668",
      fatherOfConfession: " 01226704646",
      servantFollowing: "أ. مينا نادى",
      chomosya: "",
      school: "الجلاء التجريبية",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "محتاج يكون ليه أصحاب",
      lastupdate: "42673"
    },
    {
      counter: "34",
      class: "3",
      zone: "C",
      name: "مارتن امير ",
      buildingNumber: "4",
      streetName: "شارع زغلول",
      floorNumber: "1",
      flatNumber: "1",
      MobilePhone: "( والدتة) 01226704646",
      HomePhone: "25886882",
      birthDate: "36818",
      fatherOfConfession: "",
      servantFollowing: "أ. بيشوى",
      chomosya: "",
      school: "صحارة للغات",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "بيحضر فى معهد الدراسات فى الشرابية فى ميعاد الخدمة",
      lastupdate: ""
    },
    {
      counter: "35",
      class: "3",
      zone: "C",
      name: "يوسف سامح",
      buildingNumber: "13",
      streetName: "صبرى ",
      floorNumber: "8",
      flatNumber: "81",
      MobilePhone: "01273074257",
      HomePhone: "27863747",
      birthDate: "",
      fatherOfConfession: "ابونا اسطفانوس (المنسى )",
      servantFollowing: "أ. بيتر ",
      chomosya: "غير مرشوم ",
      school: "المارونية",
      facebook: "youssef farouk ",
      email: "",
      fatherPhone: "",
      motherPhone: "01094829904",
      notes: "باباه شغال بره - بيروح كنيسة فى باب الشعرية",
      lastupdate: "42673"
    },
    {
      counter: "36",
      class: "3",
      zone: "C",
      name: "مينــا صفـوت ثـابت",
      buildingNumber: "32",
      streetName: "حمدي",
      floorNumber: "5",
      flatNumber: "ش",
      MobilePhone: "01287241617",
      HomePhone: "",
      birthDate: "37290",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. بيشوى",
      chomosya: "ابصالتس",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "1225601263",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "37",
      class: "3",
      zone: "D",
      name: "امجد منصور",
      buildingNumber: "3",
      streetName: "عطفية بكر القذاذ- الجيش",
      floorNumber: "الاخير",
      flatNumber: "ش",
      MobilePhone: "01275233037",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "أ. مينا نادى",
      chomosya: "ابصالتس",
      school: "عمر بن العاص",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "مشاكل فى البيت",
      lastupdate: "42673"
    },
    {
      counter: "38",
      class: "3",
      zone: "D",
      name: "مارك ميلاد",
      buildingNumber: "58",
      streetName: "بورسعيد ( برج المنير ) ",
      floorNumber: "7",
      flatNumber: "",
      MobilePhone: "01069527849",
      HomePhone: "24237623",
      birthDate: "36983",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. إبراهيم",
      chomosya: "غير مرشوم ",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "39",
      class: "3",
      zone: "D",
      name: "مارك عماد",
      buildingNumber: "21",
      streetName: "ابن الرشيد - جزيرة بدران - شبرا",
      floorNumber: "4",
      flatNumber: "19",
      MobilePhone: "01223247600",
      HomePhone: "",
      birthDate: "36684",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "أ. بيتر ",
      chomosya: "ابصالتس",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "والده توفى فى حادثة - قريب ستيفن",
      lastupdate: "42673"
    },
    {
      counter: "40",
      class: "3",
      zone: "D",
      name: "صموئيل عيد",
      buildingNumber: "4",
      streetName: "شارع جعفر ",
      floorNumber: "الارضى ",
      flatNumber: "",
      MobilePhone: "01116187247",
      HomePhone: "",
      birthDate: "17/9/2001",
      fatherOfConfession: "لا يوجد",
      servantFollowing: "أ. إبراهيم",
      chomosya: "غير مرشوم ",
      school: "غمرة ثانوية بنين",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "عنده مشكلة كبيرة و محتاجين نحط اسمه على المذبح",
      lastupdate: "24/10/2015"
    },
    {
      counter: "41",
      class: "3",
      zone: "D",
      name: "ميخائيل عادل",
      buildingNumber: "13",
      streetName: "شارع صافى الدين المهرانى - بستان المهاميز",
      floorNumber: "3",
      flatNumber: "6",
      MobilePhone: "01149967188",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "أبونا مسى - الفجالة",
      servantFollowing: "أ. بيتر ",
      chomosya: "شماس",
      school: "صحارا",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "بيروح الفجالة أكتر فى الشتاء و بيجيلنا قليل",
      lastupdate: "15-11-2016"
    },
    {
      counter: "42",
      class: "3",
      zone: "D",
      name: "جرجس صبحي",
      buildingNumber: "6",
      streetName: "عطفة الخربوطلي - الظاهر",
      floorNumber: "",
      flatNumber: "",
      MobilePhone: "01283631901",
      HomePhone: "",
      birthDate: "18/11/2001",
      fatherOfConfession: "ابونا انجيلوس",
      servantFollowing: "",
      chomosya: "غير مرشوم ",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "43",
      class: "3",
      zone: "D",
      name: "وليد مجدي (وليد عياد)",
      buildingNumber: "",
      streetName: "",
      floorNumber: "",
      flatNumber: "",
      MobilePhone: "01285391390",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "44",
      class: "3",
      zone: "D",
      name: "ابانوب عيسى",
      buildingNumber: "",
      streetName: "",
      floorNumber: "",
      flatNumber: "",
      MobilePhone: "",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "45",
      class: "3",
      zone: "D",
      name: "كيرلس جورج",
      buildingNumber: "",
      streetName: "",
      floorNumber: "",
      flatNumber: "",
      MobilePhone: "01226972349",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "46",
      class: "3",
      zone: "",
      name: "باسم أيمن ",
      buildingNumber: "",
      streetName: "",
      floorNumber: "",
      flatNumber: "",
      MobilePhone: "",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    },
    {
      counter: "47",
      class: "3",
      zone: "",
      name: "شنودة عازر",
      buildingNumber: "",
      streetName: "",
      floorNumber: "",
      flatNumber: "",
      MobilePhone: "01275801312",
      HomePhone: "",
      birthDate: "",
      fatherOfConfession: "",
      servantFollowing: "",
      chomosya: "",
      school: "",
      facebook: "",
      email: "",
      fatherPhone: "",
      motherPhone: "",
      notes: "",
      lastupdate: ""
    }
  ];
  let CLIENT = {
    Name: "",
    Info: "",
    GraduationYearID: {},
    AddressID: {},
    Email: "",
    LocationX: 0,
    LocationY: 0,
    Notes: "",
    fatherOfConfession: {},
    servantFollowing: {},
    Status: "",
    chomosya: true,
    MobilePhone: 0,
    HomePhone: 0,
    birthDate: new Date(),
    fatherPhone: 0,
    motherPhone: 0,
    Class: {}
  };
  Connection.query("SELECT * FROM Clients", function(error, results, fields) {
    if (error) throw error;
    console.log("The solution is: ", results);
    res.send(results);
  });
});
module.exports = router;
