module.exports.CLIENT_TABLE = {
  TableName: `Clients`,
  ID: 'ID',
  ClientName: `ClientName`,
  ClientInfo: `ClientInfo`,
  ClientGraduationYearID: `ClientGraduationYearID`,
  ClientEmail: `ClientEmail`,
  ClientLocationX: `ClientLocationX`,
  ClientLocationY: `ClientLocationY`,
  ClientNote: `ClientNote`,
  ClientsFatherOfConfession: `ClientsFatherOfConfession`,
  ClientServantFollowing: `ClientServantFollowing`,
  clientCategoryID: `clientCategoryID`,
  ClientChomosya: `ClientChomosya`,
  ClientMobilePhone: `ClientMobilePhone`,
  ClientHomePhone: `ClientHomePhone`,
  ClientbirthDate: `ClientbirthDate`,
  ClientFatherPhone: `ClientFatherPhone`,
  ClientMotherPhone: `ClientMotherPhone`,
  ClientClass: `ClientClass`,
  ClientZone: `ClientZone`,
  ClientstreetName: `ClientstreetName`,
  ClientFloorNumber: `ClientFloorNumber`,
  ClientBuildingNumber: `ClientBuildingNumber`,
  ClientFlatNumber: `ClientFlatNumber`,
  ClientStreetDetails: `ClientStreetDetails`,
  ClientSchoolID: `ClientSchoolID`
};
